# vulkan
if(APPLE)
  find_package(Vulkan 1.3.216)
  if(Vulkan_FOUND)
    set(LV_ENABLE_PORTABILITY ON CACHE BOOL "")
  else()
    find_package(Vulkan 1.3.0)
    if (Vulkan_FOUND)
      set(LV_ENABLE_PORTABILITY ON CACHE BOOL "")
    else()
      message(FATAL_ERROR "fail to find vulkan")
    endif()
  endif()
elseif(WIN32)
  find_package(Vulkan 1.3.0)
  if(NOT Vulkan_FOUND)
    message(FATAL_ERROR "fail to find vulkan")
  endif()
endif()